
services:
  - type: web
    name: meu-app
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev libopenblas-dev liblapack-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
