services:
  - type: web
    name: gestaopatio-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        value: troque-por-uma-chave-secreta
      - key: DATABASE_URL
        fromDatabase:
          name: gestaopatio-db
          property: connectionString

databases:
  - name: gestaopatio-db
    databaseName: gestaopatio
    user: gestaopatio_user
